/* soapWKWebServiceSOAP11BindingProxy.h
   Generated by gSOAP 2.8.111 for zzsdzfp.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapWKWebServiceSOAP11BindingProxy_H
#define soapWKWebServiceSOAP11BindingProxy_H
#include "soapH.h"

    class SOAP_CMAC WKWebServiceSOAP11BindingProxy : public soap {
      public:
        /// Endpoint URL of service 'WKWebServiceSOAP11BindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in zzsdzfp.h, if any
        /// Construct a proxy with new managing context
        WKWebServiceSOAP11BindingProxy();
        /// Copy constructor
        WKWebServiceSOAP11BindingProxy(const WKWebServiceSOAP11BindingProxy& rhs);
        /// Construct proxy given a managing context
        WKWebServiceSOAP11BindingProxy(const struct soap&);
        /// Construct proxy given a managing context and endpoint URL
        WKWebServiceSOAP11BindingProxy(const struct soap&, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        WKWebServiceSOAP11BindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        WKWebServiceSOAP11BindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        WKWebServiceSOAP11BindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        WKWebServiceSOAP11BindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context
        virtual ~WKWebServiceSOAP11BindingProxy();
        /// Initializer used by constructors
        virtual void WKWebServiceSOAP11BindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual WKWebServiceSOAP11BindingProxy *copy();
        /// Copy assignment
        WKWebServiceSOAP11BindingProxy& operator=(const WKWebServiceSOAP11BindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'doService' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int doService(_ns1__doService *ns1__doService, _ns1__doServiceResponse &ns1__doServiceResponse) { return this->doService(NULL, NULL, ns1__doService, ns1__doServiceResponse); }
        /// Web service synchronous operation 'doService' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int doService(const char *soap_endpoint_url, const char *soap_action, _ns1__doService *ns1__doService, _ns1__doServiceResponse &ns1__doServiceResponse) { return this->send_doService(soap_endpoint_url, soap_action, ns1__doService) || this->recv_doService(ns1__doServiceResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_doService' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_doService(const char *soap_endpoint_url, const char *soap_action, _ns1__doService *ns1__doService);
        /// Web service asynchronous operation 'recv_doService' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_doService(_ns1__doServiceResponse &ns1__doServiceResponse);
        //
        /// Web service synchronous operation 'doService' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int doService_(_ns1__doService *ns1__doService, _ns1__doServiceResponse &ns1__doServiceResponse) { return this->doService_(NULL, NULL, ns1__doService, ns1__doServiceResponse); }
        /// Web service synchronous operation 'doService' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int doService_(const char *soap_endpoint_url, const char *soap_action, _ns1__doService *ns1__doService, _ns1__doServiceResponse &ns1__doServiceResponse) { return this->send_doService_(soap_endpoint_url, soap_action, ns1__doService) || this->recv_doService_(ns1__doServiceResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_doService' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_doService_(const char *soap_endpoint_url, const char *soap_action, _ns1__doService *ns1__doService);
        /// Web service asynchronous operation 'recv_doService' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_doService_(_ns1__doServiceResponse &ns1__doServiceResponse);
    };
#endif
