/* soapWKWebServiceSOAP11BindingProxy.cpp
   Generated by gSOAP 2.8.111 for zzsdzfp.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapWKWebServiceSOAP11BindingProxy.h"

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy() : soap(SOAP_IO_DEFAULT)
{	WKWebServiceSOAP11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(const WKWebServiceSOAP11BindingProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
}

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(const struct soap &_soap) : soap(_soap)
{ }

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(const struct soap &_soap, const char *soap_endpoint_url) : soap(_soap)
{
	soap_endpoint = soap_endpoint_url;
}

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(const char *soap_endpoint_url) : soap(SOAP_IO_DEFAULT)
{	WKWebServiceSOAP11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(soap_mode iomode) : soap(iomode)
{	WKWebServiceSOAP11BindingProxy_init(iomode, iomode);
}

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(const char *soap_endpoint_url, soap_mode iomode) : soap(iomode)
{	WKWebServiceSOAP11BindingProxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	WKWebServiceSOAP11BindingProxy_init(imode, omode);
}

WKWebServiceSOAP11BindingProxy::~WKWebServiceSOAP11BindingProxy()
{
	this->destroy();
}

void WKWebServiceSOAP11BindingProxy::WKWebServiceSOAP11BindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "ns1", "http://impl.service.tax.inspur", NULL, NULL },
        { NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this, namespaces);
}

WKWebServiceSOAP11BindingProxy *WKWebServiceSOAP11BindingProxy::copy()
{	WKWebServiceSOAP11BindingProxy *dup = SOAP_NEW_UNMANAGED(WKWebServiceSOAP11BindingProxy(*(struct soap*)this));
	return dup;
}

WKWebServiceSOAP11BindingProxy& WKWebServiceSOAP11BindingProxy::operator=(const WKWebServiceSOAP11BindingProxy& rhs)
{	soap_done(this);
	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void WKWebServiceSOAP11BindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void WKWebServiceSOAP11BindingProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	WKWebServiceSOAP11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void WKWebServiceSOAP11BindingProxy::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *WKWebServiceSOAP11BindingProxy::soap_header()
{	return this->header;
}

::SOAP_ENV__Fault *WKWebServiceSOAP11BindingProxy::soap_fault()
{	return this->fault;
}

const char *WKWebServiceSOAP11BindingProxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this);
}

const char *WKWebServiceSOAP11BindingProxy::soap_fault_string()
{	return ::soap_fault_string(this);
}

const char *WKWebServiceSOAP11BindingProxy::soap_fault_detail()
{	return ::soap_fault_detail(this);
}

int WKWebServiceSOAP11BindingProxy::soap_close_socket()
{	return ::soap_closesock(this);
}

int WKWebServiceSOAP11BindingProxy::soap_force_close_socket()
{	return ::soap_force_closesock(this);
}

void WKWebServiceSOAP11BindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void WKWebServiceSOAP11BindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *WKWebServiceSOAP11BindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int WKWebServiceSOAP11BindingProxy::send_doService(const char *soap_endpoint_url, const char *soap_action, _ns1__doService *ns1__doService)
{
	struct soap *soap = this;
	struct __ns1__doService soap_tmp___ns1__doService;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService";
	if (soap_action == NULL)
		soap_action = "urn:doService";
	soap_tmp___ns1__doService.ns1__doService = ns1__doService;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__doService(soap, &soap_tmp___ns1__doService);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__doService(soap, &soap_tmp___ns1__doService, "-ns1:doService", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__doService(soap, &soap_tmp___ns1__doService, "-ns1:doService", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int WKWebServiceSOAP11BindingProxy::recv_doService(_ns1__doServiceResponse &ns1__doServiceResponse)
{
	struct soap *soap = this;
	ns1__doServiceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__doServiceResponse.soap_get(soap, "ns1:doServiceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WKWebServiceSOAP11BindingProxy::send_doService_(const char *soap_endpoint_url, const char *soap_action, _ns1__doService *ns1__doService)
{
	struct soap *soap = this;
	struct __ns1__doService_ soap_tmp___ns1__doService_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService";
	if (soap_action == NULL)
		soap_action = "urn:doService";
	soap_tmp___ns1__doService_.ns1__doService = ns1__doService;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__doService_(soap, &soap_tmp___ns1__doService_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__doService_(soap, &soap_tmp___ns1__doService_, "-ns1:doService", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__doService_(soap, &soap_tmp___ns1__doService_, "-ns1:doService", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int WKWebServiceSOAP11BindingProxy::recv_doService_(_ns1__doServiceResponse &ns1__doServiceResponse)
{
	struct soap *soap = this;
	ns1__doServiceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__doServiceResponse.soap_get(soap, "ns1:doServiceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
