/* zzsdzfp.h
   Generated by wsdl2h 2.8.111 from http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService?wsdl and typemap.dat
   2021-02-07 10:24:25 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on zzsdzfp.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://impl.service.tax.inspur                                           *
 *                                                                            *
\******************************************************************************/

/* WSDL Documentation:

WKWebService
*/


/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

ns1 = "http://impl.service.tax.inspur"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://impl.service.tax.inspur"
//gsoap ns1   schema namespace:	http://impl.service.tax.inspur
//gsoap ns1   schema form:	qualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


class _ns1__doService;

class _ns1__doServiceResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://impl.service.tax.inspur                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://impl.service.tax.inspur                                           *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://impl.service.tax.inspur":doService
/// @brief "http://impl.service.tax.inspur":doService is a complexType.
///
/// @note class _ns1__doService operations:
/// - _ns1__doService* soap_new__ns1__doService(soap*) allocate and default initialize
/// - _ns1__doService* soap_new__ns1__doService(soap*, int num) allocate and default initialize an array
/// - _ns1__doService* soap_new_req__ns1__doService(soap*, ...) allocate, set required members
/// - _ns1__doService* soap_new_set__ns1__doService(soap*, ...) allocate, set all public members
/// - _ns1__doService::soap_default(soap*) default initialize members
/// - int soap_read__ns1__doService(soap*, _ns1__doService*) deserialize from a stream
/// - int soap_write__ns1__doService(soap*, _ns1__doService*) serialize to a stream
/// - _ns1__doService* _ns1__doService::soap_dup(soap*) returns deep copy of _ns1__doService, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__doService::soap_del() deep deletes _ns1__doService data members, use only after _ns1__doService::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__doService::soap_type() returns SOAP_TYPE__ns1__doService or derived type identifier
class _ns1__doService
{ public:
/// Element "xml" of type xs:string.
    char*                                xml                            0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://impl.service.tax.inspur":doServiceResponse
/// @brief "http://impl.service.tax.inspur":doServiceResponse is a complexType.
///
/// @note class _ns1__doServiceResponse operations:
/// - _ns1__doServiceResponse* soap_new__ns1__doServiceResponse(soap*) allocate and default initialize
/// - _ns1__doServiceResponse* soap_new__ns1__doServiceResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__doServiceResponse* soap_new_req__ns1__doServiceResponse(soap*, ...) allocate, set required members
/// - _ns1__doServiceResponse* soap_new_set__ns1__doServiceResponse(soap*, ...) allocate, set all public members
/// - _ns1__doServiceResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__doServiceResponse(soap*, _ns1__doServiceResponse*) deserialize from a stream
/// - int soap_write__ns1__doServiceResponse(soap*, _ns1__doServiceResponse*) serialize to a stream
/// - _ns1__doServiceResponse* _ns1__doServiceResponse::soap_dup(soap*) returns deep copy of _ns1__doServiceResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__doServiceResponse::soap_del() deep deletes _ns1__doServiceResponse data members, use only after _ns1__doServiceResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__doServiceResponse::soap_type() returns SOAP_TYPE__ns1__doServiceResponse or derived type identifier
class _ns1__doServiceResponse
{ public:
/// Element "return" of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://impl.service.tax.inspur                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://impl.service.tax.inspur                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	WKWebServiceSOAP11Binding 
//gsoap ns1  service type:	WKWebServicePortType 
//gsoap ns1  service port:	http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService 
//gsoap ns1  service namespace:	http://impl.service.tax.inspur 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_documentation Documentation
WKWebService

@section Service_bindings Service Bindings

  - @ref WKWebServiceSOAP11Binding

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page WKWebServiceSOAP11Binding Binding "WKWebServiceSOAP11Binding"

@section WKWebServiceSOAP11Binding_operations Operations of Binding "WKWebServiceSOAP11Binding"

  - @ref __ns1__doService

  - @ref __ns1__doService_

@section WKWebServiceSOAP11Binding_ports Default endpoints of Binding "WKWebServiceSOAP11Binding"

  - http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService

@note Multiple service bindings collected as one, use wsdl2h option -Nname to produce a separate service for each binding


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   WKWebServiceSOAP11Binding                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__doService                                                         *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__doService" of service binding "WKWebServiceSOAP11Binding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService

  - Default SOAP action or REST location path:
    - "urn:doService"

  - Addressing input action: "urn:doService"

  - Addressing output action: "urn:doServiceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__doService(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__doService*                    ns1__doService,
    // output parameters:
    _ns1__doServiceResponse            &ns1__doServiceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__doService(
    struct soap *soap,
    // input parameters:
    _ns1__doService*                    ns1__doService,
    // output parameters:
    _ns1__doServiceResponse            &ns1__doServiceResponse
  );
@endcode

C++ proxy class (defined in soapWKWebServiceSOAP11BindingProxy.h generated with soapcpp2):
@code
  class WKWebServiceSOAP11BindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWKWebServiceSOAP11BindingService.h generated with soapcpp2):
@code
  class WKWebServiceSOAP11BindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	doService SOAP
//gsoap ns1  service method-style:	doService document
//gsoap ns1  service method-encoding:	doService literal
//gsoap ns1  service method-input-action:	doService urn:doService
//gsoap ns1  service method-output-action:	doService urn:doServiceResponse
int __ns1__doService(
    _ns1__doService*                    ns1__doService,	///< Input parameter
    _ns1__doServiceResponse            &ns1__doServiceResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__doService_                                                        *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__doService_" of service binding "WKWebServiceSOAP11Binding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://111.202.226.69:8001/ZZSDZFP_TBKP_SPBM/services/WKWebService

  - Default SOAP action or REST location path:
    - "urn:doService"

  - Addressing input action: "urn:doService"

  - Addressing output action: "urn:doServiceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__doService_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__doService*                    ns1__doService,
    // output parameters:
    _ns1__doServiceResponse            &ns1__doServiceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__doService_(
    struct soap *soap,
    // input parameters:
    _ns1__doService*                    ns1__doService,
    // output parameters:
    _ns1__doServiceResponse            &ns1__doServiceResponse
  );
@endcode

C++ proxy class (defined in soapWKWebServiceSOAP11BindingProxy.h generated with soapcpp2):
@code
  class WKWebServiceSOAP11BindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWKWebServiceSOAP11BindingService.h generated with soapcpp2):
@code
  class WKWebServiceSOAP11BindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	doService_ SOAP
//gsoap ns1  service method-style:	doService_ document
//gsoap ns1  service method-encoding:	doService_ literal
//gsoap ns1  service method-input-action:	doService_ urn:doService
//gsoap ns1  service method-output-action:	doService_ urn:doServiceResponse
int __ns1__doService_(
    _ns1__doService*                    ns1__doService,	///< Input parameter
    _ns1__doServiceResponse            &ns1__doServiceResponse	///< Output parameter
);

/** @page WKWebServiceSOAP11Binding Binding "WKWebServiceSOAP11Binding"

@section WKWebServiceSOAP11Binding_policy_enablers Policy Enablers of Binding "WKWebServiceSOAP11Binding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section ns1 Top-level root elements of schema "http://impl.service.tax.inspur"

  - <ns1:doService> @ref _ns1__doService
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__doService(struct soap*, _ns1__doService*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__doService(struct soap*, _ns1__doService*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__doService(struct soap*, const char *URL, _ns1__doService*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__doService(struct soap*, const char *URL, _ns1__doService*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__doService(struct soap*, const char *URL, _ns1__doService*);
    soap_POST_recv__ns1__doService(struct soap*, _ns1__doService*);
    @endcode

  - <ns1:doServiceResponse> @ref _ns1__doServiceResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__doServiceResponse(struct soap*, _ns1__doServiceResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__doServiceResponse(struct soap*, _ns1__doServiceResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__doServiceResponse(struct soap*, const char *URL, _ns1__doServiceResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__doServiceResponse(struct soap*, const char *URL, _ns1__doServiceResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__doServiceResponse(struct soap*, const char *URL, _ns1__doServiceResponse*);
    soap_POST_recv__ns1__doServiceResponse(struct soap*, _ns1__doServiceResponse*);
    @endcode

*/

/* End of zzsdzfp.h */
