DocumentRoot /home/ubuntu/website/myteam/frontend/dist
<Directory "/home/ubuntu/website/myteam/frontend/dist">
	Options Indexes FollowSymLinks
	AllowOverride All 
	Require all granted
</Directory>

# webapi
<IfModule alias_module>
	Alias /api /usr/local/backend/api
    
	<Directory "/usr/local/backend/api">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# test
<IfModule alias_module>
	Alias /test /usr/local/backend/test
    
	<Directory "/usr/local/backend/test">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# upload
<IfModule alias_module>
	Alias /upload /usr/local/backend/upload
	
	<Directory "/usr/local/backend/upload">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>
