#
# This file loads knewcode of the modules included with the Apache HTTP
# Server itself.
# Copy To /etc/httpd/conf.modules.d
#

AddHandler dlib_kc_extname .kc
dlib_kc_path /usr/local/knewcode
dlib_kc_framework "kc_framework"
LoadModule dlib_kc_module "/usr/local/knewcode/kc_apache_mod.so"
