# sudo cp ./kc_site.conf /etc/apache2/sites-available/
# sudo a2ensite kc_site.conf

# 添加响应头：允许前端多线程访问共享内存
#Header set Cross-Origin-Opener-Policy "same-origin"
#Header set Cross-Origin-Embedder-Policy "require-corp"

#Define PORT 25360
<VirtualHost *:25360>
	# 主目录
	DocumentRoot ${prjPth}/frontend/dist
	<Directory "${prjPth}/frontend/dist">
		#Options Indexes FollowSymLinks
		Options FollowSymLinks
		AllowOverride All 
		Require all granted
	</Directory>

	###_api
	<IfModule alias_module>
		Alias /api ${prjPth}/backend/api
		
		<Directory "${prjPth}/backend/api">
			AllowOverride FileInfo
			Require all granted
		</Directory>
	</IfModule>

	# inside api
	<IfModule alias_module>
		Alias /inside ${prjPth}/backend/inside
		
		<Directory "${prjPth}/backend/inside">
			AllowOverride FileInfo
			Require all granted
		</Directory>
	</IfModule>

	# upload
	<IfModule alias_module>
		Alias /upload ${prjPth}/upload
		
		<Directory ${prjPth}/upload>
			AllowOverride FileInfo
			Require all granted
		</Directory>
	</IfModule>

	# test
	<IfModule alias_module>
		Alias /test ${prjPth}/backend/test
		
		<Directory "${prjPth}/backend/test">
			AllowOverride FileInfo
			Require all granted
		</Directory>
	</IfModule>

	# bin
	<IfModule alias_module>
		Alias /bin ${binPth}
		
		<Directory "${binPth}">
			AllowOverride FileInfo
			Require all granted
		</Directory>
	</IfModule>
</VirtualHost>

