Define PORT 5995
Define SSL_PORT 5665
Define PROXY_PORT 5885
Define prjPth "D:\work\MY2301MakeKC\trunk"

# 加载正常apache配置文件
Include conf/httpd.conf

# 添加响应头：允许前端多线程访问共享内存
Header set Cross-Origin-Opener-Policy "same-origin"
Header set Cross-Origin-Embedder-Policy "require-corp"

# 加载knewcode
<IfDefine prjPth>
Include ../../../conf/knewcode.conf
</IfDefine>

# 主目录
DocumentRoot ${prjPth}/frontend/dist
<Directory "${prjPth}/frontend/dist">
	#Options Indexes FollowSymLinks
	Options FollowSymLinks
    AllowOverride All 
	Require all granted
</Directory>

# webapi
<IfModule alias_module>
	Alias /api ${prjPth}/backend/api
    
	<Directory "${prjPth}/backend/api">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# inside api
<IfModule alias_module>
	Alias /inside ${prjPth}/backend/inside
    
	<Directory "${prjPth}/backend/inside">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# Dynamic Linking Library
<IfModule alias_module>
	Alias /bin ${prjPth}/backend/bin
    
	<Directory "${prjPth}/backend/bin">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# test
<IfModule alias_module>
	Alias /test ${prjPth}/backend/test
    
	<Directory "${prjPth}/backend/test">
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# upload
<IfModule alias_module>
	Alias /upload ${prjPth}/prj/website/upload
    
	<Directory ${prjPth}/prj/website/upload>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>
