Define PORT 23901
Define SSL_PORT 23902
Define PROXY_PORT 23903
Define prjPth "D:\work\my2103saas_backend\trunk"

# 加载正常apache配置文件
Include conf/httpd.conf

# 加载knewcode
<IfDefine prjPth>
Include ../../../conf/knewcode.conf
</IfDefine>

DocumentRoot "${prjPth}\frontend\dist"
<Directory />
    #AllowOverride none
    #Require all denied
	Options Indexes FollowSymLinks
    AllowOverride FileInfo
    Require all granted
	#Header set Access-Control-Allow-Origin *
	#Header set Access-Control-Allow-Credentials true
</Directory>

# webapi
<IfModule alias_module>
	Alias /api ${prjPth}\api
    
	<Directory /api>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# inside
<IfModule alias_module>
	Alias /inside ${prjPth}\inside
    
	<Directory /api>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# test
<IfModule alias_module>
	Alias /test ${prjPth}\test
    
	<Directory /test>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# upload
<IfModule alias_module>
	Alias /upload ${prjPth}\upload
    
	<Directory /upload>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# test2
<IfModule alias_module>
	Alias /test2 htdocs
    
	<Directory /test2>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>

# bin
<IfModule alias_module>
	Alias /bin ${prjPth}\bin
    
	<Directory /bin>
		AllowOverride FileInfo
		Require all granted
	</Directory>
</IfModule>
