#
# This file loads knewcode of the modules included with the Apache HTTP
# Server itself.
#

AddHandler dlib_kc_extname .kc
LoadModule dlib_kc_module "${binPth}/kc_apache_mod.dll"

dlib_kc_path "${binPth}"
dlib_kc_config "${prjPth}/my-prj.xml"
